Revert "Revert "Merge branch 'upstream' into jenner""
This reverts commit e347c495ad2615d725864eeb481f20fb64e9e8f8.

diff --git a/client/scripts/freebsd b/client/scripts/freebsd
--- a/client/scripts/freebsd
+++ b/client/scripts/freebsd
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $Id: freebsd,v 1.13.2.7 2004/09/30 23:22:48 dhankins Exp $
+# $Id: freebsd,v 1.22 2008/05/23 13:56:07 fdupont Exp $
 #
 # $FreeBSD$
 
@@ -12,24 +12,65 @@ fi
 
 make_resolv_conf() {
   if [ x"$new_domain_name_servers" != x ]; then
-    if [ "x$new_domain_name" != x ]; then
-      ( echo search $new_domain_name >/etc/resolv.conf )
-      exit_status=$?
+    ( cat /dev/null > /etc/resolv.conf.dhclient )
+    exit_status=$?
+    if [ $exit_status -ne 0 ]; then
+      $LOGGER "Unable to create /etc/resolv.conf.dhclient: Error $exit_status"
     else
-      if [ -e /etc/resolv.conf ] ; then
-	( rm /etc/resolv.conf )
+      if [ "x$new_domain_search" != x ]; then
+	( echo search $new_domain_search >> /etc/resolv.conf.dhclient )
 	exit_status=$?
-      else
-	( touch /etc/resolv.conf )
+      elif [ "x$new_domain_name" != x ]; then
+	# Note that the DHCP 'Domain Name Option' is really just a domain
+	# name, and that this practice of using the domain name option as
+	# a search path is both nonstandard and deprecated.
+	( echo search $new_domain_name >> /etc/resolv.conf.dhclient )
 	exit_status=$?
       fi
-    fi
-    if [ $exit_status -ne 0 ]; then
-      $LOGGER "WARNING: Unable to update resolv.conf: Error $exit_status"
-    else
       for nameserver in $new_domain_name_servers; do
-	( echo nameserver $nameserver >>/etc/resolv.conf )
+	if [ $exit_status -ne 0 ]; then
+	  break
+	fi
+	( echo nameserver $nameserver >>/etc/resolv.conf.dhclient )
+	exit_status=$?
       done
+
+      # If there were no errors, attempt to mv the new file into place.
+      if [ $exit_status -eq 0 ]; then
+	( mv /etc/resolv.conf.dhclient /etc/resolv.conf )
+	exit_status=$?
+      fi
+
+      if [ $exit_status -ne 0 ]; then
+	$LOGGER "Error while writing new /etc/resolv.conf."
+      fi
+    fi
+  elif [ "x${new_dhcp6_name_servers}" != x ] ; then
+    ( cat /dev/null > /etc/resolv.conf.dhclient6 )
+    exit_status=$?
+    if [ $exit_status -ne 0 ] ; then
+      $LOGGER "Unable to create /etc/resolv.conf.dhclient6: Error $exit_status"
+    else
+      if [ "x${new_dhcp6_domain_search}" != x ] ; then
+	( echo search ${new_dhcp6_domain_search} >> /etc/resolv.conf.dhclient6 )
+	exit_status=$?
+      fi
+      for nameserver in ${new_dhcp6_name_servers} ; do
+	if [ $exit_status -ne 0 ] ; then
+	  break
+	fi
+        ( echo nameserver ${nameserver} >> /etc/resolv.conf.dhclient6 )
+	exit_status=$?
+      done
+
+      if [ $exit_status -eq 0 ] ; then
+        ( mv /etc/resolv.conf.dhclient6 /etc/resolv.conf )
+	exit_status=$?
+      fi
+
+      if [ $exit_status -ne 0 ] ; then
+	$LOGGER "Error while writing new /etc/resolv.conf."
+      fi
     fi
   fi
 }
@@ -82,6 +123,10 @@ if [ x$reason = xMEDIUM ]; then
   sleep 1
   exit_with_hooks 0
 fi
+
+###
+### DHCPv4 Handlers
+###
 
 if [ x$reason = xPREINIT ]; then
   if [ x$alias_ip_address != x ]; then
@@ -141,6 +186,12 @@ if [ x$reason = xBOUND ] || [ x$reason = xRENEW ] || \
     fi
     route add $new_ip_address 127.1 >/dev/null 2>&1
     for router in $new_routers; do
+      # If the subnet is captive, eg the netmask is /32 but the default
+      # gateway is (obviously) outside of this, then we need to produce a
+      # host route to reach the gateway.
+      if [ "x$new_subnet_mask" = "x255.255.255.255" ] ; then
+	route add -host $router -interface $interface
+      fi
       route add default $router >/dev/null 2>&1
     done
     if [ -n "$new_static_routes" ]; then
@@ -212,6 +263,9 @@ if [ x$reason = xTIMEOUT ]; then
       fi
       route add $new_ip_address 127.1 >/dev/null 2>&1
       for router in $new_routers; do
+	if [ "x$new_subnet_mask" = "x255.255.255.255" ] ; then
+	  route add -host $router -interface $interface
+	fi
 	route add default $router >/dev/null 2>&1
       done
       set -- $new_static_routes
@@ -237,6 +291,70 @@ if [ x$reason = xTIMEOUT ]; then
   arp -n -a | sed -n -e 's/^.*(\(.*\)) at .*$/arp -d \1/p' \
 							|sh >/dev/null 2>&1
   exit_with_hooks 1
+fi
+
+###
+### DHCPv6 Handlers
+###
+
+if [ ${reason} = PREINIT6 ] ; then
+  # Ensure interface is up.
+  ifconfig ${interface} up
+
+  # XXX: Remove any stale addresses from aborted clients.
+
+  exit_with_hooks 0
+fi
+
+if [ x${old_ip6_prefix} != x ] || [ x${new_ip6_prefix} != x ] ; then
+    echo Prefix ${reason} old=${old_ip6_prefix} new=${new_ip6_prefix}
+
+    exit_with_hooks 0
+fi
+
+if [ ${reason} = BOUND6 ] ; then
+  if [ x${new_ip6_address} = x ] || [ x${new_ip6_prefixlen} = x ] ; then
+    exit_with_hooks 2;
+  fi
+
+  ifconfig ${interface} inet6 ${new_ip6_address}/${new_ip6_prefixlen} alias
+
+  # Check for nameserver options.
+  make_resolv_conf
+
+  exit_with_hooks 0
+fi
+
+if [ ${reason} = RENEW6 ] || [ ${reason} = REBIND6 ] ; then
+  # Make sure nothing has moved around on us.
+
+  # Nameservers/domains/etc.
+  if [ "x${new_dhcp6_name_servers}" != "x${old_dhcp6_name_servers}" ] ||
+     [ "x${new_dhcp6_domain_search}" != "x${old_dhcp6_domain_search}" ] ; then
+    make_resolv_conf
+  fi
+
+  exit_with_hooks 0
+fi
+
+if [ ${reason} = DEPREF6 ] ; then
+  if [ x${new_ip6_address} = x ] ; then
+    exit_with_hooks 2;
+  fi
+
+  ifconfig ${interface} inet6 ${new_ip6_address} deprecated
+
+  exit_with_hooks 0
+fi
+
+if [ ${reason} = EXPIRE6 -o ${reason} = RELEASE6 -o ${reason} = STOP6 ] ; then
+  if [ x${old_ip6_address} = x ] || [ x${old_ip6_prefixlen} = x ] ; then
+    exit_with_hooks 2;
+  fi
+
+  ifconfig ${interface} inet6 ${old_ip6_address}/${old_ip6_prefixlen} -alias
+
+  exit_with_hooks 0
 fi
 
 exit_with_hooks 0
